# -*- coding: utf-8 -*-
"""SIF2500385_Individual Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maZJim3q4SkrPx3NA9dbYXvLbLB7H7kz
"""

print("Restuarent Ordering System")
user_name ="lily"
your_id="13"
orders = []
order_id = 1

while True:
 user=input("Your Username: ")
 login_id=input("Enter Your ID: ")

 if user == user_name and login_id == your_id:
    print("Logging Successful...")
    break

 else:
    print("Error,try again...")

food = {
    1:{"food_type":"Fried Rice","price":800,"number":50},
    2:{"food_type":"Pasta","price":500,"number":20},
    3:{"food_type":"Kottu","price":700,"number":50}
}

def Add_Order():
    global order_id

    print("\nFoods and Prices details")

    for number,details in food.items():

      print("\nFood Number:",number)
      print("Food:",details["food_type"])
      print("Price:Rs.",details["price"])
      print("Available:",details["number"])

    while True:
      try:
        choice = int(input("\nEnter Food Number:"))
        quantity = int(input("Enter quantity"))

        if quantity <=0:
          print("Quantity must be greater than 0")
          continue
        break

      except ValueError:
          print("Please enter number only")


    if choice in food:
      if quantity <= food[choice]["number"]:

        order = {
          "Order ID": order_id,
          "Food": food[choice]["food_type"],
          "Quantity": quantity,
          "Amount": food[choice]["price"] * quantity,
          "Status": "Pending"
         }

        orders.append(order)

        food[choice]["number"] -= quantity

        print("Order Added Successfuly")
        print("Your Order ID:",order_id)

        order_id += 1

      else:
        print("Not enough stock")

    else:
     print("Invalid food number")


def View_Order():
  if not orders:
    print("No order available")

  else:
    for order in orders:
      print(order)

def Find_Order(search):

    for order in orders:
      if order["Order ID"] == search:
        return order

    return None


def Search_Order():
    try:
      search = int(input("Enter Order ID: "))

      order = Find_Order(search)

      if order:
          print(order)
      else:
          print("Order not found")

    except ValueError:
      print("Please enter number only")


def Update_Order_Status():
    try:

       search = int(input("Enter Order ID: "))

       order = Find_Order(search)

       if order:
            status = input("Enter status (Pending/Completed):")
            if status not in ["Pending","Completed"]:
              print("Invalid status")
              return
            order["Status"] = status
            print("Status Updated")

       else:
          print("Order not found")

    except ValueError:
      print("Please enter number only")


def Sales_and_Count():
  total = 0
  count = 0

  for order in orders:
    if order["Status"] == "Completed":
      total += order["Amount"]
      count += 1

  print("Total Sales: Rs.",total)
  print("Completed Orders:",count)


def Payment():

  try:

    search = int(input("Enter Order ID: "))
    order = Find_Order(search)

    if order:
      if "Payment" in order:
          print("Payment already completed")
          return
      print("Amount to pay: Rs.",order["Amount"])

      method = input("Enter payment method(Cash/Card):")
      if method not in ["Cash","Card"]:
        print("Invali payment")
        return

      order["Payment"]=method
      print("Payment completed")

    else:
      print("Order not found")

  except ValueError:
    print("Please enter numbers only")



while True:

  print("\n-MENU-")
  print("\n1.Add Order")
  print("\n2.View Order")
  print("\n3.Search Order")
  print("\n4.Update Order Status")
  print("\n5.Sales and Count")
  print("\n6.Payment")
  print("\n7.Exit")

  try:
      choice=int(input("Enter your choice number:"))

      if choice==1:
          Add_Order()

      elif choice==2:
          View_Order()

      elif choice==3:
          Search_Order()

      elif choice==4:
          Update_Order_Status()

      elif choice==5:
          Sales_and_Count()

      elif choice==6:
          Payment()

      elif choice==7:
          print("Exit")
          break

      else:
        print("Invalid choice")

  except ValueError:
    print("Please enter number only")

